default_stages: [commit, manual]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
  - repo: local
    hooks:
      - id: code-coverage-bump
        name: "Code Coverage Bump"
        language: system
        entry: ./coverage_bump.py
        always_run: false
