default_stages: [commit, manual]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-vet
      # - id: go-unit-tests
      # - id: go-build
      # - id: go-mod-tidy
  - repo: local
    hooks:
      - id: license
        name: "Licence check"
        language: system
        always_run: false
        pass_filenames: false
        entry: make license-check
      - id: code-coverage-bump-aws
        name: "Code Coverage Bump AWS"
        language: system
        entry: make coverage-bump PLATFORM=aws
        always_run: false
        pass_filenames: false
      - id: code-coverage-bump-aws
        name: "Code Coverage Bump GCP"
        language: system
        entry: make coverage-bump PLATFORM=gcp
        always_run: false
        pass_filenames: false
