on:
  push:
    branches:
      - master
    paths-ignore:
      - "tools/**"
      - "Makefile"
      - "test_integration.sh"
      - "test.http"
      - "README.md"
      - "LICENSE*.md"
      - ".dockerignore"
      - ".pre-commit-config.yaml"
      - ".gitignore"
  pull_request:
    branches:
      - master
    types:
      - opened

name: Deployment

jobs:
  test-n-push:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [aws, gcp]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: make test PLATFORM=${{matrix.platform}}

      - name: Auth with docker hub
        run: echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USER}" --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: make build PLATFORM=${{matrix.platform}}

      - name: Push image to the repo
        run: |
          make push PLATFORM=${{matrix.platform}}
          make push-latest PLATFORM=${{matrix.platform}}
