on:
  push:
    branches:
      - master
    paths-ignore:
      - "tools/**"
      - "Makefile"
      - "test_integration.sh"
      - "test.http"
      - "README.md"
      - "LICENSE*.md"
      - ".dockerignore"
      - ".pre-commit-config.yaml"
      - ".gitignore"
  pull_request:
    branches:
      - master
    types:
      - opened

name: Deployment

jobs:
  test-n-push:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: make test

      - name: Auth with docker hub
        run: docker login -u {{ secrets.DOCKER_USER }} -p {{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: make build

      - name: Push image to the repo
        run: make push
